$('#MainContent_Anrede').val('Herr')
$('#MainContent_Vorname').val('Mohamed')
$('#MainContent_Nachname').val('Shaban')
$('#MainContent_Strasse').val('173 El Haram Street, El Haram, Giza, Egypt')
$('#MainContent_Ort').val('12111, Cairo')
$('#MainContent_Telefon').val('+201111167934')
$('#MainContent_EMail').val('mohamedtarekmahmoud@gmail.com')
$('#MainContent_Day').val('18')
$('#MainContent_Month').val('03')
$('#MainContent_Year').val('1992')
$('#MainContent_wo').val('TUM')
$('#MainContent_kaution').val('1100')
$('#MainContent_Aufnahmebedingung').val('Ja ich bin Student in Muenchen (TUM LMU, FH Muenchen)')
$('#MainContent_Student').val('Ja ich Studiere und habe einen Studentenausweis max 6 Monate alt')
$('#MainContent_Alter').val('Ja ich bin Student mit Studentenausweis Muenchen zwischen 18-27 Jahre alt.')
$('#MainContent_Bedingung1').val('Ja ich weiss, daß meine Daten ueberprueft werden')
$('#MainContent_Bedingung2').val('Ja ich kenne die Bedingungen und weiss, dass ich KEIN WIDERUFSRECHT habe.')
$('#MainContent_Reservierungsart').val('Verbindlich für 150 Euro reservieren, es gibt KEIN WIDERUFSRECHT')
$('#MainContent_Rauchen').val('Ja ich rauche nicht im Gebäude.')
$('#MainContent_ENDE').val('3 VON 01.09.2015 BIS: 29.11.2015')
